Description: TODO
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: Name of the stage

Globals:
  Function:
    Runtime: nodejs14.x
    Tracing: Active

Resources:
  BoilerplateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/handlers/http/
      Handler: example.get
      Events:
        PostVoteEvent:
          Type: Api
          Properties:
            Path: /example
            Method: get

  # Boilerplate for IAM role to enable logging
  CloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  Account:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt CloudWatchRole.Arn

#Outputs: # You should specify the Stack's external interfaces as Outputs
