Description: Lambda task for TPM-1496
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs14.x
    Tracing: Active
    Tags:
      owner: dhirajnair
      purpose: TPM-1496


Resources:
  FlaggedWordsScannerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FlaggedWordsScannerFunction
      CodeUri: ./build/handlers/sqs/
      Handler: index.handler
      Policies:
      - SQSPollerPolicy:
          QueueName:
            !GetAtt TPM1496SqsQueue.QueueName
      - SNSPublishMessagePolicy:
          TopicName:
            !GetAtt TPM1496SnsTopic.TopicName
      - CloudWatchPutMetricPolicy: {}
      Tags:
        owner: dhirajnair
        purpose: 'TPM-1496'

  TPM1496SqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: TPM1496SqsQueue
      DelaySeconds: 0
      VisibilityTimeout: 120
      Tags:
        - Value: "dhirajnair"
          Key: "owner"
        - Value: "TPM-1496"
          Key: "purpose"

  TPM1496SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: TPM1496SnsTopic
      Tags:
        - Value: "dhirajnair"
          Key: "owner"
        - Value: "TPM-1496"
          Key: "purpose"


  FlaggedWordsScannerFunctionEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !GetAtt TPM1496SqsQueue.Arn
      FunctionName: !GetAtt FlaggedWordsScannerFunction.Arn
